---

- hosts: "all"
  gather_facts: false
  become: false
  vars:
    ansible_user: "root"
  tasks:
    - name: "Overwrite ansible user from vars and execute as root"
      ansible.builtin.set_fact:
        ansible_user: "root"
      tags:
        - "execute_as_root"

    - name: "Test SSH connection"
      ansible.builtin.ping:
      ignore_unreachable: "true"
      ignore_errors: "true"
      changed_when: "false"
      register: "playbook_add_automation_user_ssh_test"
      tags:
        - "check_root_access"

    - name: "Add new user accounts"
      block:
        - name: "Install sudo"
          ansible.builtin.include_role:
            name: "univention.ucs_roles.univention_install"
          vars:
            univention_install_name: "sudo"
          tags:
            - "univention_install"
            - "univention_install_sudo"

        - name: "Add user (univention)"
          ansible.builtin.include_role:
            name: "univention.ucs_roles.add_local_user"
          vars:
            add_local_user_user: "{{ univention_ansible_user }}"
          when: "univention_ansible_user is defined"
          tags:
            - "add_local_user"
            - "add_local_user_univention"
      when: "playbook_add_automation_user_ssh_test.unreachable is not defined"
