---

collections:
  # 3rd party
  - name: "ansible.utils"
    version: "2.1.0"
  - name: "ansible.netcommon"
    version: "2.0.2"
  - name: "ansible.posix"
    version: "1.2.0"
  - name: "community.general"
    version: "3.0.1"
  - name: "community.crypto"
    version: "1.6.2"
  # univention
  - name: "univention.ucs_roles"
    version: "1.42.0"
  - name: "univention.ucs_modules"
    version: "1.0.0"
