---

#############################################################
## Ansible configuration                                   ##
#############################################################

# Description: Ansbile root password after changing it from default value
ansible_become_password: "{{ ansible_become_password_vault }}"

# Description: Local user after changing it from default value
univention_ansible_user:
  name: "univention_ansible"
  comment: "Univention ansible user"
  password: "{{ ansible_become_password|password_hash('sha512') }}"
  sshkey_file: "id_ed25519_ucs_kvm_image.pub"

# Description: The Ansible user name to execute `playbook_bootstrap_ucs.yml`
#              playbook
automation_ansible_user: "{{ univention_ansible_user.name }}"
